### ISSUE TITLE
macOS Catalina - [TcpAdapterProxy.cpp.o] Error 1 when 'make' 

### ISSUE THREAD

**Issue by RogerBackwards** [aws-samples/aws-iot-securetunneling-localproxy#21]
Hi, i'm working on macOS Catalina 10.15.3. 
I did follow all the steps, and all dependencies installed, but when I do 'make' localproxy at 7% it says:
`[  7%] Building CXX object CMakeFiles/localproxytest.dir/src/TcpAdapterProxy.cpp.o`
AND:
`/Volumes/Transcend/Feina/Inteleen/Raspian/dependencies/aws-iot-securetunneling-localproxy/src/TcpAdapterProxy.cpp:234:105: error: 
      lambda capture 'tac' is not used [-Werror,-Wunused-lambda-capture]
  ...tcp_write_buffer_drain_complete, then_what, &tac]()
                                               ~~~^~~
/Volumes/Transcend/Feina/Inteleen/Raspian/dependencies/aws-iot-securetunneling-localproxy/src/TcpAdapterProxy.cpp:1142:31: error: 
      lambda capture 'ec' is not used [-Werror,-Wunused-lambda-capture]
                [this, &tac, &ec]()
                           ~~~^~
/Volumes/Transcend/Feina/Inteleen/Raspian/dependencies/aws-iot-securetunneling-localproxy/src/TcpAdapterProxy.cpp:1158:43: error: 
      lambda capture 'ec' is not used [-Werror,-Wunused-lambda-capture]
                            [this, &tac, &ec]()
                                       ~~~^~
/Volumes/Transcend/Feina/Inteleen/Raspian/dependencies/aws-iot-securetunneling-localproxy/src/TcpAdapterProxy.cpp:1201:43: error: 
      lambda capture 'ec' is not used [-Werror,-Wunused-lambda-capture]
                            [this, &tac, &ec]()
                                       ~~~^~
/Volumes/Transcend/Feina/Inteleen/Raspian/dependencies/aws-iot-securetunneling-localproxy/src/TcpAdapterProxy.cpp:1218:47: error: 
      lambda capture 'ec' is not used [-Werror,-Wunused-lambda-capture]
                                [this, &tac, &ec]()
                                           ~~~^~
5 errors generated.
make[2]: *** [CMakeFiles/localproxytest.dir/src/TcpAdapterProxy.cpp.o] Error 1
make[1]: *** [CMakeFiles/localproxytest.dir/all] Error 2
make: *** [all] Error 2`

I don't even know what should I try right now. No clue.

When I installed openssl I did configure: 
`./Configure darwin64-x86_64-cc shared enable-ec_nistp_64_gcc_128 no-ssl2 no-ssl3 no-comp --openssldir=/usr/local/ssl/macos-x86_64`

**Comment by RogerBackwards** [comment]
> I have same issue,But my make process reported error at 23%, the error similar

Hi same here, but if i repeat the 'make' again it happens at 7%

**Comment by HarshGandhi-AWS** [comment]
Hello @RogerBackwards ,
Hello @brilliantwf ,

Thank you for your feedback. This issue was present for devices running on MacOS. I have made some updates in code which will resolve this issue. Please clone the latest commit and let me know if you are still facing any issue. 

Thank you,
Harsh Gandhi
