### ISSUE TITLE
fails to build with boost 1.87 as they removed deprecated rfc2818_verification.hpp

### ISSUE THREAD

**Issue by thomas-roos** [aws-samples/aws-iot-securetunneling-localproxy#172]
```
| In file included from /codebuild/output/src3203205847/src/actions-runner/_work/meta-aws/meta-aws/build/tmp/work/cortexa57-poky-linux/aws-iot-securetunneling-localproxy/git/git/src/WebProxyAdapter.h:5,
|                  from /codebuild/output/src3203205847/src/actions-runner/_work/meta-aws/meta-aws/build/tmp/work/cortexa57-poky-linux/aws-iot-securetunneling-localproxy/git/git/src/WebProxyAdapter.cpp:4:
| /codebuild/output/src3203205847/src/actions-runner/_work/meta-aws/meta-aws/build/tmp/work/cortexa57-poky-linux/aws-iot-securetunneling-localproxy/git/git/src/LocalproxyConfig.h:20:10: fatal error: boost/asio/ssl/rfc2818_verification.hpp: No such file or directory
|    20 | #include <boost/asio/ssl/rfc2818_verification.hpp>
|       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| compilation terminated.
```
-> 1.87 change log  * Removed deprecated class `ssl::rfc2818_verification`.
-> use the "drop in" replacement `ssl::host_name_verification`
-> meta-aws for yocto master use now boost 1.87 - failed here: https://github.com/aws4embeddedlinux/meta-aws/actions/runs/12730636133/job/35483803506

**Comment by ig15** [comment]
Local proxy has been updated to support Boost 1.87 and related API updates:
https://github.com/aws-samples/aws-iot-securetunneling-localproxy/pull/175

**Comment by thomas-roos** [comment]
Thank you, tested it, works.
